# Generated by Django 3.1.3 on 2021-02-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=140, unique=True)),
                ('carname', models.CharField(max_length=140)),
                ('model', models.IntegerField()),
                ('km', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ownership', models.CharField(choices=[('First Owner', 'First Owner'), ('Second Owner', 'Second Owner'), ('Third Owner', 'Third Owner')], default=1, max_length=12)),
                ('reg_number', models.CharField(max_length=140)),
                ('color', models.CharField(max_length=140)),
                ('tyre_condition', models.CharField(max_length=140)),
                ('replacement', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=20)),
                ('accident_history', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=20)),
                ('car_condition', models.CharField(choices=[('Excellent Condition', 'Excellent Condition'), ('Hale And Hearty', 'Hale And Hearty'), ('ShowRoom Condition', 'ShowRoom Condition')], default=1, max_length=120)),
                ('insurance', models.CharField(choices=[('New Insurance', 'New Insurance'), ('Valid Insurance', 'Valid Insurance')], default=1, max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CreateNewPostPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Front_Side_Image', models.ImageField(upload_to='Images')),
                ('Back_Side_Image', models.ImageField(upload_to='Images')),
                ('Left_Side_Image', models.ImageField(upload_to='Images')),
                ('Right_Side_Image', models.ImageField(upload_to='Images')),
                ('Car_Interior_Image', models.ImageField(upload_to='Images')),
                ('Car_Stereo_And_Camera', models.ImageField(upload_to='Images')),
                ('Car_Seat_Image', models.ImageField(upload_to='Images')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.createnewpost')),
            ],
        ),
    ]
